"""
Kitsune-TTS Symbol Coverage Test
Tests that all phonemes generated by espeak for EN, PT-BR, and JA
are covered by our symbols.py table. Any missing symbol = silent letter during training.
"""
import sys
import os
sys.path.insert(0, os.path.abspath('.'))
os.environ['PHONEMIZER_ESPEAK_LIBRARY'] = r"C:\Program Files\eSpeak NG\libespeak-ng.dll"
os.environ['PHONEMIZER_ESPEAK_PATH'] = r"C:\Program Files\eSpeak NG\espeak-ng.exe"

from kitsune.data.symbols import symbols, _symbol_to_id, cleaned_text_to_sequence, sequence_to_text

# ============================================================
# Test phrases - covering diverse phonetic content per language
# ============================================================

test_phrases = {
    "en": [
        "Yes, but not very often.",
        "Hello! I am Emilia. This is my very first test.",
        "The quick brown fox jumps over the lazy dog.",
        "She sells seashells by the seashore.",
        "I think therefore I am.",
        "Would you like a cup of tea?",
        "The weather is beautiful today.",
        "Let me remind you. I asked you to stay behind.",
        "In exactly the same way we were friends.",
        "That's a very thoughtful thing to say.",
    ],
    "pt-br": [
        "Olá, eu sou a Emília!",
        "O rato roeu a roupa do rei de Roma.",
        "Bom dia, como você está?",
        "Eu preciso ir ao supermercado comprar pão.",
        "A noite está linda e cheia de estrelas.",
        "Você consegue me ouvir claramente?",
        "O João comeu pão com manteiga na manhã.",
        "Ela não sabia o que fazer naquela situação.",
    ],
    "ja": [
        "Watashi wa Emilia desu.",
        "Konnichiwa, hajimemashite.",
        "Arigatou gozaimasu.",
        "Subaru-kun, daisuki desu!",
        "Nani wo shite imasu ka?",
    ],
}

# ============================================================
# Run phonemizer and check coverage
# ============================================================

from kitsune.phonemizer.phonemizer import EspeakPhonemizer

# Build phonemizer - skip JA if not available
try:
    phonemizer = EspeakPhonemizer()
    available_langs = ["en", "pt-br", "ja"]
except Exception:
    from phonemizer.backend import EspeakBackend
    class PartialPhonemizer:
        def __init__(self):
            self.backends = {
                "en": EspeakBackend("en-us", language_switch='remove-flags'),
                "pt-br": EspeakBackend("pt-br", language_switch='remove-flags'),
            }
        def phonemize(self, text, lang="pt-br"):
            text = text.lower().strip()
            import re
            text = re.sub(r'\s+', ' ', text)
            if lang not in self.backends:
                lang = "pt-br"
            backend = self.backends[lang]
            phonemes_str = backend.phonemize([text], strip=True)[0]
            phonemes_str = phonemes_str.replace(" ", "")
            return list(phonemes_str)
    phonemizer = PartialPhonemizer()
    available_langs = ["en", "pt-br"]
    print("⚠️  Japonês não disponível neste sistema (espeak sem voz 'ja'). Testando EN + PT-BR.\n")

print("=" * 70)
print("🦊 KITSUNE-TTS - TESTE DE COBERTURA DE SÍMBOLOS")
print("=" * 70)
print(f"\nTotal de símbolos na tabela: {len(symbols)}")
print(f"Símbolos: {''.join(symbols[1:])}")  # skip _pad
print()

all_missing = set()
all_seen = set()
total_phonemes = 0
total_kept = 0

for lang in available_langs:
    phrases = test_phrases.get(lang, [])
    if not phrases:
        continue
        
    print(f"\n{'='*70}")
    print(f"🌐 IDIOMA: {lang.upper()}")
    print(f"{'='*70}")
    
    lang_missing = set()
    lang_seen = set()
    
    for phrase in phrases:
        raw_phonemes = phonemizer.phonemize(phrase, lang=lang)
        filtered = cleaned_text_to_sequence(raw_phonemes)
        recovered = sequence_to_text(filtered)
        
        # Find missing symbols
        missing_in_phrase = set()
        for ph in raw_phonemes:
            all_seen.add(ph)
            lang_seen.add(ph)
            total_phonemes += 1
            if ph in _symbol_to_id:
                total_kept += 1
            else:
                missing_in_phrase.add(ph)
                lang_missing.add(ph)
                all_missing.add(ph)
        
        status = "✅" if not missing_in_phrase else "❌"
        print(f"\n{status} \"{phrase}\"")
        print(f"   IPA bruto : {''.join(raw_phonemes)}")
        print(f"   Filtrado  : {recovered}")
        if missing_in_phrase:
            print(f"   ⚠️ PERDIDOS: {missing_in_phrase}")
    
    print(f"\n--- Resumo {lang.upper()} ---")
    print(f"Fonemas únicos vistos: {len(lang_seen)} → {lang_seen}")
    if lang_missing:
        print(f"❌ FONEMAS FALTANDO: {lang_missing}")
    else:
        print(f"✅ COBERTURA 100%! Nenhum fonema perdido.")

# ============================================================
# Final Summary
# ============================================================
print(f"\n{'='*70}")
print(f"📊 RESUMO FINAL")
print(f"{'='*70}")
print(f"Total de fonemas processados: {total_phonemes}")
print(f"Total mantidos pela tabela : {total_kept}")
print(f"Total PERDIDOS             : {total_phonemes - total_kept}")
coverage = (total_kept / total_phonemes * 100) if total_phonemes > 0 else 0
print(f"Cobertura                  : {coverage:.1f}%")
print(f"\nFonemas únicos encontrados : {len(all_seen)}")
print(f"Fonemas na tabela          : {len(symbols)}")

if all_missing:
    print(f"\n❌ FONEMAS QUE PRECISAM SER ADICIONADOS AO symbols.py:")
    for m in sorted(all_missing):
        print(f"   '{m}' (U+{ord(m):04X})")
    print(f"\nAdicione esses ao _vowels ou _consonants em symbols.py ANTES de treinar!")
else:
    print(f"\n✅ TABELA PERFEITA! Cobertura 100% em todos os idiomas testados.")
    print(f"   Pode treinar sem medo! 🚀")
